---
- name: routing
  become: true
  hosts: all
  tasks:

#  - name: Set up NAT on inetRouter
#    template: 
#      src: "templates/{{ item.src }}"
#      dest: "{{ item.dest }}"
#      owner: root
#      group: root
#      mode: "{{ item.mode }}"
#    with_items:
#      - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
#      - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
#    when: (ansible_hostname == "inetRouter")

  - name: set iptables-persistent
    apt: 
      name: iptables-persistent
      state: present
    when: (ansible_hostname == "inetRouter")

  - name: enable MASQUERADE
    command: iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o enp0s3 -j MASQUERADE
    when: (ansible_hostname == "inetRouter")

  - name: save iptables rules
    shell: iptables-save -c  > /etc/iptables_rules.ipv4
    when: (ansible_hostname == "inetRouter")
  
  - name: stop UFW
    command: systemctl stop ufw.service

  - name: disable UFW
    command: systemctl disable ufw.service

  - name: set up forward packages across routers
    sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
    when: "'routers' in group_names"
  
  - name: disable default route
    copy: 
      src: "templates/00-installer-config.yaml"
      dest: "/etc/netplan/00-installer-config.yaml"
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname != "inetRouter") 

  - name: add default gateway for centralRouter
    template: 
      src: "50-vagrant_{{ansible_hostname}}.yaml"
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644

  - name: restart all hosts
    reboot:
       reboot_timeout: 600